sudo: false

language: julia

notifications:
  email: false

env:
  matrix:
    - JULIAVERSION="juliareleases"
    - JULIAVERSION="julianightlies"

script:
  - julia -e 'Pkg.init(); Pkg.add("BinDeps"); Pkg.clone(pwd()); Pkg.build("OptimPack"); Pkg.test("OptimPack")'

